// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEb4zSTpOxeQdV3tSdLVCYhA-Pt3jgNxQ',
    appId: '1:92948989694:web:85416116cef8b992a6c7af',
    messagingSenderId: '92948989694',
    projectId: 'project1-533e1',
    authDomain: 'project1-533e1.firebaseapp.com',
    storageBucket: 'project1-533e1.firebasestorage.app',
    measurementId: 'G-SDF57VR2YM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmm5eb8opxpikyor9kXg3MyLxsujGwZs8',
    appId: '1:92948989694:android:cbbffa675562cc2fa6c7af',
    messagingSenderId: '92948989694',
    projectId: 'project1-533e1',
    storageBucket: 'project1-533e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBimexvS8AocfsDM-cFnb8EWZpYd4dGIjc',
    appId: '1:92948989694:ios:f8e7480acd90fd17a6c7af',
    messagingSenderId: '92948989694',
    projectId: 'project1-533e1',
    storageBucket: 'project1-533e1.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBimexvS8AocfsDM-cFnb8EWZpYd4dGIjc',
    appId: '1:92948989694:ios:f8e7480acd90fd17a6c7af',
    messagingSenderId: '92948989694',
    projectId: 'project1-533e1',
    storageBucket: 'project1-533e1.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEb4zSTpOxeQdV3tSdLVCYhA-Pt3jgNxQ',
    appId: '1:92948989694:web:d5233000b1720b83a6c7af',
    messagingSenderId: '92948989694',
    projectId: 'project1-533e1',
    authDomain: 'project1-533e1.firebaseapp.com',
    storageBucket: 'project1-533e1.firebasestorage.app',
    measurementId: 'G-STZQY1BSTR',
  );
}
